language: python
python: 3.7

cache:
  - pip

install:
  - python -m pip install nox

script:
  - nox -s build

deploy:
  provider: script
  on:
    branch: master
    repo: sethmlarson/sethmlarson.dev
  script:
    -